import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widget from "../components/Widget";
import { sanityClient } from "../sanity.js";
import { Tweet } from "../typing";
import { fetchComments } from "../utils/fetchComments";
import { fetchTweets } from "../utils/fetchTweets";

interface Props {
  tweets: Tweet[];
}
const Home = ({ tweets }: Props) => {
  return (
    <div className="w-full h-fit bg-gray-800 text-white">
      <Head>
        <title>Duitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" grid grid-cols-7 lg:grid-cols-10 max-w-5xl h-full mx-auto bg-gray-800">
        {/* ---------------------------- Sidebar --------------------------- */}
        <Sidebar />

        {/* ----------------------------- Feed ----------------------------- */}
        <Feed tweets={tweets} />
        {/* ---------------------------- Widget ---------------------------- */}
        <Widget />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const tweets = await fetchTweets();
  return {
    props: {
      tweets,
    },
  };
};
